### ISSUE TITLE
Add Airplay button and support

### ISSUE THREAD

**Issue by tensafefrogs** [googleads/google-media-framework-ios#12]
We should support Airplay when it's available.

An Airplay button should appear on the control bar, and while playing on the Airplay device, the video should have some sort of overlay letting the viewer know.

**Comment by hyurtseven81** [comment]
+1

**Comment by shawnbuso** [comment]
Hi all,

Reaching out to see if there are still folks interested in this. If you are, reply here to let us know and we can look into prioritizing it. If not we may mark this obsolete.

Thanks!
Shawn
