### ISSUE TITLE
Support for live streams

### ISSUE THREAD

**Issue by tensafefrogs** [googleads/google-media-framework-ios#59]
We should add support for live streams.

This should include a UI update to support the different use cases:
- Show some sort of "Live" indicator in the player control bar
- A "go to live" button/option when watching the previous content in a live stream (say you are watching a live event but seek back a few minutes - sometimes you want to skip back to the "current" time in the stream)
- Seekbar "loaded" indication should fill in from the right side, with the playhead starting at the far right. The "go to live" could simply be seeking all the way to the right.
- Seeking into an unloaded segment (aka seeking all the way to the left) should not be allowed

Anything else we need to think about before getting started?

Here's a live test stream we can use:
https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

**Comment by shawnbuso** [comment]
Hi all,

Since this has been open for so long we're re-evaluating the demand for it. If you're interested in this as a feature please respond here to let us know.

Thanks!
Shawn
