### ISSUE TITLE
Content playback stalls occasionally on device

### ISSUE THREAD

**Issue by tensafefrogs** [googleads/google-media-framework-ios#66]
I'm investigating an issue where content playback doesn't resume after a preroll, and only on a device (I'm not able to reproduce in the simulator).

It seems to be related to the ads request starting before the content is buffered (We optimistically start loading content at the same time as the ads request).

The fix will likely involve requesting the content after the ads are complete, but I'm still investigating.

**Comment by shawnbuso** [comment]
We haven't had reports of this from any of our users, and it's 3 years old, so I'm marking obsolete. If anyone is seeing this please let us know and we'll look into it.
