### ISSUE TITLE
GMF - DRM Management

### ISSUE THREAD

**Issue by ldi13** [googleads/google-media-framework-ios#68]
Hello GMF Team,

I plan for my next app to embed GMF Framework on iOS.
I would like to know if it's possible with the player to handle DRM management ?

I didn't see any point mentioning that into the documentation.

Thank you by advance for your answer,

Best regards,

Lorenzo.

**Comment by hyurtseven81** [comment]
There is an MpegDash + Widevine sample but it just an  example without any functionality, it would be good that support integrated in GMF

**Comment by shawnbuso** [comment]
Hi all,

If you're still interested in DRM support, could you let us know which specific DRM server you're using so we can investigate adding support?

Thanks!
