### ISSUE TITLE
Does not display midrolls

### ISSUE THREAD

**Issue by josueruiz7** [googleads/google-media-framework-ios#70]
With the new version of IMASDK, the GMF does not display mid-rolls.

I have found the solution, but I can't push the solution.

Regads.

**Comment by charlesweill** [comment]
Could you please make a pull request? I'll gladly have a look.

**Comment by josueruiz7** [comment]
Thanks you! :)

**Comment by charlesweill** [comment]
@josueruiz7: My teams noticed that you hadn't signed a Contributor License Agreement for making contributions to Google repositories yet. Please fill out either the individual or corporate CLA.

If you are an individual writing original source code and you're sure you own the intellectual property, then you'll need to sign an individual CLA available at http://code.google.com/legal/individual-cla-v1.0.html (Note the form at the bottom of the page which allows you to sign electronically).
If you work for a company that wants to allow you to contribute your work to this client library, then you'll need to sign a corporate CLA available at http://code.google.com/legal/corporate-cla-v1.0.html.

For more information, please see https://github.com/googleads/google-media-framework-ios/blob/master/CONTRIBUTING.md

**Comment by josueruiz7** [comment]
![screen shot 2015-10-06 at 10 33 08 am](https://cloud.githubusercontent.com/assets/1444007/10315147/bd722d58-6c15-11e5-9841-c3fca09bd6d8.png)

Hi, I have signed an Individual Agreements.

Regards.

**Comment by charlesweill** [comment]
Thank you kindly. And great work spotting and fixing this bug.
