### ISSUE TITLE
There is no play buttn after resume ad redirect

### ISSUE THREAD

**Issue by hyurtseven81** [googleads/google-media-framework-ios#72]
When you clicking the show more info on ad and return to player you can't do anything

**Comment by Seenu16** [comment]
+1

What's the status on this?

**Comment by shawnbuso** [comment]
Hi there,

Sorry about the delay on this - this will be fixed by #86. When you come back from an ad, tapping on the player will show the controls, and you can click the play button to resume the ad.

Shawn
