### ISSUE TITLE
GMFPlayerOverlayViewController.loadView will always override custom playerOverlayView

### ISSUE THREAD

**Issue by bigluck** [googleads/google-media-framework-ios#74]
I would replace the default view `playerOverlayView` used by `GMFPlayerOverlayViewController` without override the class, I've written:

``` objective-c
GMFPlayerViewController *videoPlayerViewController = [[GMFPlayerViewController alloc] init];
GMFPlayerOverlayViewController *overlayViewController = [[GMFPlayerOverlayViewController alloc] init];
overlayViewController.playerOverlayView = [[MyCustomOverlay alloc] init];
videoPlayerViewController.videoPlayerOverlayViewController = overlayViewController;
```

but didn't work because `[GMFPlayerOverlayViewController loadView]` always override `_playerOverlayView` with the default `GMFPlayerOverlayView`, even if `_playerOverlayView` is already set.

**Comment by shawnbuso** [comment]
Thanks for the report - this will be fixed by #98.
