### ISSUE TITLE
Replace Minimize button for a fullscreen toggle button

### ISSUE THREAD

**Issue by kazo0** [googleads/google-media-framework-ios#80]
The minimize button at the bottom left of the player should be replaced with a toggle to force the player  into fullscreen mode, at least notifying the view that the container should be re-arranged since fullscreen was requested

**Comment by shawnbuso** [comment]
Hi all,

Since this has been open for so long we're re-evaluating the demand for it. If you're interested in this as a feature please respond here to let us know.

Thanks!
Shawn
