### ISSUE TITLE
Cocoapods update error

### ISSUE THREAD

**Issue by lzanol** [googleads/google-media-framework-ios#83]
Hello,

When running `pod install` with Cocoapods' new version (1.0.0), GoogleMediaFrameworkDemo build won't work. It seems to complain about wrong `-lPods` compiler flag.

Best regards,
Leandro

**Comment by shawnbuso** [comment]
Are you seeing this after adding a target to the Podfile? I'm getting an error about that because we don't currently specify a target, but once I update that everything is running fine.

**Comment by lzanol** [comment]
Exactly. I added `target "GoogleMediaFrameworkDemo" do ...` just to run the sample app.

**Comment by Seenu16** [comment]
I had the same problem. Fixed by removing libPods.a from project folders

**Comment by shawnbuso** [comment]
Sounds like potentially an XCode caching issue - @lzanol did this resolve the issue for you?

**Comment by lzanol** [comment]
@shawnbuso Actually I gave up going this way, I've created a project from scratch and embedded GMF source together with my code into it.

**Comment by shawnbuso** [comment]
Ah ok sorry to hear that it didn't work out - if you need anything else from us let us know.

**Comment by lzanol** [comment]
@shawnbuso Ok, thank you so much for the support. Regards.
