### ISSUE TITLE
Connecting/Removing headphone app crash

### ISSUE THREAD

**Issue by Seenu16** [googleads/google-media-framework-ios#87]
While connecting/removing head phone app crashes with below error

(lldb) bt
- thread #17: tid = 0x23a56, 0x00000001803e8158 libobjc.A.dylib`objc_release + 8, name = 'AVAudioSession Notify Thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x100000000)
  - frame #0: 0x00000001803e8158 libobjc.A.dylib`objc_release + 8
    frame #1: 0x00000001001220e4 TimesNow`GMFAudioRouteChangeListenerCallback(inClientData=0x00000001405f6ef0, inID=1919902568, inDataSize=8, inData=5 key/value pairs) + 272 at GMFVideoPlayer.m:48
    frame #2: 0x0000000183674fe0 AudioToolbox`AudioSessionPropertyListeners::CallPropertyListenersImp(unsigned int, unsigned int, void const*) + 352
    frame #3: 0x0000000183674da4 AudioToolbox`AudioSessionPropertyListeners::CallPropertyListeners(unsigned int, unsigned int, void const_) + 280
    frame #4: 0x000000018356bba0 AudioToolbox`HandleCFPropertyListChange(unsigned int, unsigned long, unsigned char_, unsigned int) + 144
    frame #5: 0x0000000183674410 AudioToolbox`ProcessDeferredMessage(__CFData const*, unsigned int, unsigned int) + 912
    frame #6: 0x0000000183673d04 AudioToolbox`ASCallbackReceiver_AudioSessionPingMessage + 408
    frame #7: 0x0000000183769f6c AudioToolbox`_XAudioSessionPingMessage + 44
    frame #8: 0x000000018356b924 AudioToolbox`mshMIGPerform + 248
    frame #9: 0x0000000180d217d4 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
    frame #10: 0x0000000180d20f0c CoreFoundation`__CFRunLoopDoSource1 + 436
    frame #11: 0x0000000180d1ec64 CoreFoundation`__CFRunLoopRun + 1800
    frame #12: 0x0000000180c48c50 CoreFoundation`CFRunLoopRunSpecific + 384
    frame #13: 0x00000001873c19e0 libAVFAudio.dylib`GenericRunLoopThread::Entry(void*) + 164
    frame #14: 0x000000018739675c libAVFAudio.dylib`CAPThread::Entry(CAPThread*) + 84
    frame #15: 0x00000001809cfb28 libsystem_pthread.dylib`_pthread_body + 156
    frame #16: 0x00000001809cfa8c libsystem_pthread.dylib`_pthread_start + 156
    frame #17: 0x00000001809cd028 libsystem_pthread.dylib`thread_start + 4

**Comment by shawnbuso** [comment]
Hi there,

We had seen this issue in the past, but it should be resolved with the latest version of the IMA SDK. Are you still seeing it if you update to the latest GMF?

Thanks,
Shawn Busolits
IMA SDK Team

**Comment by shawnbuso** [comment]
Closing for lack of response - if you're still seeing this issue please let us know!
