### ISSUE TITLE
I downloaded the GoogleMediaFrameworkDemo project but it is giving errors.

### ISSUE THREAD

**Issue by sarathyarra1300** [googleads/google-media-framework-ios#89]
I downloaded the GoogleMediaFrameworkDemo project but it is giving errors.

This is how My PodFile look like:
platform :ios, ‘6.1’
target ‘GoogleMediaFrameworkDemo’ do
pod 'GoogleMediaFramework', '~> 1.0'
end

In 'VideoListController.h' it is giving error 'Unknown type name GMFIMASDKAdService, did you mean GMFAdService' on this line;
@property(nonatomic, strong) GMFIMASDKAdService *adService;

In 'VideoListController.m' it is giving error 'No visible @interface for GMFPlayerViewController declares the selector 'loadStreamWithURL:imaTag:'' on this line;
[self.videoPlayerViewController loadStreamWithURL:[NSURL URLWithString:video.videoURL] imaTag:video.adTagURL];

What should i do to resolve these errors and run the project.

**Comment by shawnbuso** [comment]
Hi there,

Unfortunately our CocoaPods release of the GMF framework is out of date, and CocoaPods pushed an update that's making it difficult for us to update it. We're still working on that, but in the mean time you can download and compile the framework from the repo *or* roll back to a version of the sample app prior to the change from GMFAdService to GMFIMASDKAdService.

Thanks,
Shawn

**Comment by shawnbuso** [comment]
This should be resolved with the latest release, done in January 2018. If you're still having trouble let us know!
