### ISSUE TITLE
NSInternalInconsistencyException There is no image called player_control_play_large

### ISSUE THREAD

**Issue by gurhub** [googleads/google-media-framework-ios#91]
Hi,

Player crashes with exception message: 

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'There is no image called player_control_play_large

I installed with cocoapods:

pod 'GoogleMediaFramework', '~> 1.0'

Xcode Version 8.2.1 (8C1002)

iOS9+ project.

I checked that example project also crashes with same exception message even if "player_control_play_large" image in project. 

Need help.

**Comment by remexon** [comment]
Change the Podfile to the following code and run pod install

------------------------------------------------------------

platform :ios, "8.0"

use_frameworks!

target "GoogleMediaFrameworkDemo" do
pod 'GoogleMediaFramework'
end

**Comment by shawnbuso** [comment]
Thanks for the suggestion, @remexon! @gurhub, did this work for you?

**Comment by remexon** [comment]
@shawnbuso @gurhub Yes, it works fine for me.

**Comment by mustafa2010** [comment]
Solution: Your App can't read image from Pod/GoogleMediaFramework/Resources
So Move images from Pod/GoogleMediaFramework/Resources to YourApp/Resources
