### ISSUE TITLE
Demo crashes when trying to show a video

### ISSUE THREAD

**Issue by dwxw** [googleads/google-media-framework-ios#92]
Just trying out the demo, but clicking any of the options causes the app to crash with:

2017-03-17 10:48:54.579992 GoogleMediaFrameworkDemo[3522:1193093] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'There is no image called player_control_play_large'

Any ideas?  I cloned the repo and used CocoaPods to build it.

**Comment by shawnbuso** [comment]
It looks like this is indeed a bug either in the demo or in the way our framework is being packaged. I'll have to look into this and see what's going on.

**Comment by dannyshmueli** [comment]
+1 when is this going to merge to master and to the cocoapod? this really makes the whole library unusable
