### ISSUE TITLE
Unexpected behaviour while hiding controls with no animation

### ISSUE THREAD

**Issue by mayur-gauswami** [googleads/google-media-framework-ios#95]
https://github.com/googleads/google-media-framework-ios/blob/919a5455653d6a838efa95ec2182d3c6c095daf0/GoogleMediaFramework/GMFPlayerOverlayViewController.m#L155

Here if i call "playerOverlayVC.hidePlayerControlsAnimated(animated: false)", it won't hide overlay controls.

In implementation, considering "animated" value as "hidden" creating this unexpected behaviour.

**Comment by shawnbuso** [comment]
Thanks for the report - this will be fixed by #97
